export const dummyUsers = [
  {
    _id: 1,
    name: 'John Travorta',
    email: 'john@email.com',
    isAdmin: false,
  },
  {
    _id: 2,
    name: 'Mariko Hanada',
    email: 'mariko@email.com',
    isAdmin: false,
  },
]

export const featuredProducts = [
  {
    id: 1,
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    brand: 'Apple',
    category: 'Electronics',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    rating: 4.5,
    numReviews: 12,
    price: 89.99,
    countInStock: 10,
    reviews: [],
  },
  {
    id: 2,
    name: 'iPhone 13 Pro 256GB Memory',
    image: '/images/phone.jpg',
    brand: 'Apple',
    category: 'Electronics',
    description:
      'Introducing the iPhone 13 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    rating: 4,
    numReviews: 8,
    price: 599.99,
    countInStock: 7,
    reviews: [],
  },
  {
    id: 3,
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    brand: 'Cannon',
    category: 'Electronics',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    rating: 3,
    numReviews: 12,
    price: 929.99,
    countInStock: 5,
    reviews: [],
  },
]
export const products = [
  {
    id: 1,
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'images/airpods.jpg',
    brand: 'Apple',
    category: 'Electronics',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    rating: 4.5,
    numReviews: 12,
    price: 89.99,
    countInStock: 10,
    reviews: [],
  },
  {
    id: 2,
    name: 'iPhone 13 Pro 256GB Memory',
    image: 'images/phone.jpg',
    brand: 'Apple',
    category: 'Electronics',
    description:
      'Introducing the iPhone 13 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    rating: 4,
    numReviews: 8,
    price: 599.99,
    countInStock: 7,
    reviews: [],
  },
  {
    id: 3,
    name: 'Cannon EOS 80D DSLR Camera',
    image: 'images/camera.jpg',
    brand: 'Cannon',
    category: 'Electronics',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    rating: 3,
    numReviews: 12,
    price: 929.99,
    countInStock: 5,
    reviews: [],
  },
  {
    id: 4,
    name: 'Amazon Echo Dot 3rd Generation',
    image: 'images/alexa.jpg',
    brand: 'Amazon',
    category: 'Electronics',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    rating: 4,
    numReviews: 12,
    price: 29.99,
    countInStock: 0,
    reviews: [],
  },
  {
    id: 5,
    name: 'Sample name',
    image: 'images/sample.jpg',
    brand: 'Sample brand',
    category: 'Sample category',
    description: 'Sample description',
    rating: 0,
    numReviews: 0,
    price: 0,
    countInStock: 0,
    reviews: [],
  },
  {
    id: 6,
    name: 'Sample name',
    image: 'images/sample.jpg',
    brand: 'Sample brand',
    category: 'Sample category',
    description: 'Sample description',
    rating: 0,
    numReviews: 0,
    price: 0,
    countInStock: 0,
    reviews: [],
  },
  {
    id: 7,
    name: 'Sample name',
    image: 'images/sample.jpg',
    brand: 'Sample brand',
    category: 'Sample category',
    description: 'Sample description',
    rating: 0,
    numReviews: 0,
    price: 0,
    countInStock: 0,
    reviews: [],
  },
  {
    id: 8,
    name: 'Sample name',
    image: 'images/sample.jpg',
    brand: 'Sample brand',
    category: 'Sample category',
    description: 'Sample description',
    rating: 0,
    numReviews: 0,
    price: 0,
    countInStock: 0,
    reviews: [],
  },
]
